site_name: MkDocs-Nature
site_author: "Waylan Limberg"
favicon: favicon.ico

repo_name: GitHub
repo_url: https://github.com/waylan/mkdocs-nature

copyright: "Copyright &copy; 2017"

theme: nature

extra:
    issue_tracker: https://github.com/waylan/mkdocs-nature/issues
    icon: icon.png
    # logo: logo.png

markdown_extensions:
    - toc:
        permalink: True
    - codehilite

pages:
    - Home: index.md
    - Features: features.md
    - About:
        - "The Project": about.md
        - Contributing: contributing.md
        - "Release Notes": release-notes.md
